const wishes=[['May friendship be your first promise.','मित्रता पहिलो वाचा बनोस्।'],['May your home be full of laughter.','तपाईंहरूको घर हाँसोले भरियोस्।'],['May you grow with kindness.','मायालु व्यवहारसँगै जीवन अघि बढोस्।'],['May joy find you in little things.','सानासाना कुरामा खुसी मिलोस्।'],['May you walk with trust.','विश्वाससँगै अघि बढ्नुहोस्।'],['May every season bring togetherness.','हरेक ऋतुमा साथ र अपनत्व रहोस्।'],['May love light every tomorrow.','प्रेमले हरेक भोलि उज्यालो बनाओस्।']];let wishIndex=0;
function renderWish(){$('#wishText').textContent=wishes[wishIndex][lang==='ne'?1:0];$('#wishButtons').innerHTML=wishes.map((_,i)=>`<button type="button" data-wish="${i}" aria-label="${lang==='ne'?'शुभकामना':'Wish'} ${digits(i+1)}" aria-pressed="${i===wishIndex}" class="${i===wishIndex?'selected':''}">${digits(i+1)}</button>`).join('');}
$('#wishButtons').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;wishIndex=+b.dataset.wish;renderWish();elapsed=0;const r=b.getBoundingClientRect();burst(r.x+r.width/2,r.y);if(soundOn)chime(.035)});
$('#timeline').addEventListener('click',e=>{const b=e.target.closest('.event');if(!b)return;const expanded=b.classList.toggle('expanded');b.setAttribute('aria-expanded',String(expanded));elapsed=0;autoReading=false;reel.classList.remove('reading')});
document.querySelectorAll('.blessing-trigger').forEach(b=>b.addEventListener('click',()=>{b.classList.remove('praised');void b.offsetWidth;b.classList.add('praised');const r=b.getBoundingClientRect();burst(r.x+r.width/2,r.y+r.height/2);toast('May Lord Ganesha bless this beginning with joy and harmony.','भगवान् गणेशले यो नयाँ सुरुवातमा खुसी र सद्भावको आशीर्वाद दिऊन्।');if(soundOn)chime(.05)}));
$('#diya').onclick=e=>{const b=e.currentTarget;const lit=b.classList.toggle('unlit');b.setAttribute('aria-pressed',String(!lit));if(!lit){const r=b.getBoundingClientRect();burst(r.x+r.width/2,r.y);toast('Your little light joins our celebration.','तपाईंको शुभकामनाको प्रकाश हाम्रो खुसीमा थपियो।');if(soundOn)chime(.04)}elapsed=0};
$('#flower').onclick=e=>{const b=e.currentTarget;b.classList.remove('scattering');void b.offsetWidth;b.classList.add('scattering');burst(innerWidth*.25,65);burst(innerWidth*.5,65);burst(innerWidth*.75,65);setTimeout(()=>b.classList.remove('scattering'),1100)};
$('#copyVenue').onclick=async()=>{try{await navigator.clipboard.writeText('Mithila Abadh Sanskritik Sanrakchan Parishad, Bajrang Chowk–8, opposite Janaki Health Care Hospital, Janakpur, Nepal');toast('Venue address copied.','समारोह स्थलको ठेगाना कपी भयो।')}catch{toast('Mithila Abadh Sanskritik Sanrakchan Parishad · Bajrang Chowk–8','मिथिला अवध सांस्कृतिक संरक्षण परिषद् · बजरंग चोक–८')}};
function fitAnnouncement(){if(!isLanding)return;const c=$('.announcement .content'),box=$('.announcement');c.style.transform='';const available=innerHeight-parseFloat(getComputedStyle(box).paddingTop)-parseFloat(getComputedStyle(box).paddingBottom);const scale=Math.min(1,available/c.scrollHeight);c.style.transform=`scale(${scale})`;}
window.addEventListener('resize',()=>{fitAnnouncement();if(opened)go(index)});document.fonts.ready.then(fitAnnouncement);
if(matchMedia('(hover:hover)').matches)reel.addEventListener('pointermove',e=>{reel.style.setProperty('--pointer-x',e.clientX+'px');reel.style.setProperty('--pointer-y',e.clientY+'px')},{passive:true});
